config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :products do
    member do
      delete :cancel
      post :select
    end
  end
  resources :machines
  root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :machine
  has_many :payments, dependent: :destroy
  has_one_attached :picture

  monetize :price_cents, as: 'price'

  after_save_commit :update_price
  after_save_commit :update_quantity

  scope :operational, -> { where(operational: true) }

  def payment
    payments.last
  end

  def update_price
    return unless saved_change_to_price_cents?

    Vending::Transport.send_message Vending::Messages.set_slection_price(price_cents, selection)
  end

  def update_quantity
    return unless saved_change_to_quantity?

    Vending::Transport.send_message Vending::Messages.set_selection_inventory(selection, quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy, :cancel, :select ]

  # GET /products or /products.json
  def index
    @products = Product.operational.page(params[:page]).per(16)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  def select
    Vending::Transport.send_message Vending::Messages.select_buy(@product.selection)

    payment = @product.payments.create(amount: @product.price, status: "queued")

    ProcessPaymentJob.perform_later(payment)
  end

  def cancel
    Vending::Transport.send_message Vending::Messages.cancel_selection

    Esocket::Transport.send_message(Esocket::Messages.cancel_transaction(@product.payment&.transaction&.transaction_id))

    redirect_to products_path
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Machine.first.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.expect(product: [ :picture, :name, :price, :selection, :quantity ])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %>
        prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-3">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div class="mb-3">
    <%= form.label :selection, style: "display: block" %>
    <%= form.number_field :selection %>
  </div>

  <div class="mb-3">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div class="mb-3">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="mb-3">
    <%= form.submit class:
                  "w-full rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm
                font-medium text-gray-900 hover:bg-gray-100 hover:text-primary-700 focus:z-10
                focus:outline-none focus:ring-4 focus:ring-gray-100 dark:border-gray-600
                dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white
                dark:focus:ring-gray-700 sm:w-auto
        " %>
  </div>
<% end %>

app/views/products/_product.html.erb
<a
  href="<%= product_path product %>"
  data-turbo="false"
  class="
    rounded border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700
    dark:bg-gray-800
  "
>
  <div class="h-56 w-full">

    <% if product.picture.attached? %>
      <%= image_tag product.picture, class: "h-full w-full" %>
    <% else %>
      <%= image_tag "image.webp", class: "h-full w-full" %>
    <% end %>
  </div>
  <div class="pt-6">

    <div
      class="
        text-lg font-semibold leading-tight text-gray-900 hover:underline
        dark:text-white
      "
    ><%= product.selection %></div>

    <div class="mt-4 flex items-center justify-between gap-4">
      <p class="text-2xl font-extrabold leading-tight text-gray-900 dark:text-white">$<%= product.price %></p>
    </div>
  </div>
</a>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
  <div class="mx-auto px-4">
    <!-- Heading & Filters -->
    <div
      class="
        mb-4 grid gap-4 sm:grid-cols-4 md:mb-8 lg:grid-cols-4 xl:grid-cols-6
      "
    >
      <%= render @products %>
    </div>

    <div class="mt-8 flex items-center justify-between">
      <%= paginate @products %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<div class="container mx-auto">
  <h1 class="mb-2">New product</h1>
  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<section
  class="py-8 bg-white md:py-16 dark:bg-gray-900 antialiased h-screen"
  data-controller="payment"
  data-payment-url-value="<%= select_product_path(@product) %>"
>
  <div class="max-w-screen-xl px-4 mx-auto 2xl:px-0">
    <div class="lg:grid lg:grid-cols-2 lg:gap-8 xl:gap-16">
      <div class="shrink-0 max-w-md lg:max-w-lg mx-auto">
        <% if @product.picture.attached? %>
          <%= image_tag @product.picture, class: "w-full" %>
        <% else %>
          <%= image_tag "image.webp", class: "w-full" %>
        <% end %>
      </div>

      <div class="mt-6 sm:mt-8 lg:mt-0">
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
          <%= @product.selection %>
        </h1>
        <div class="mt-4 sm:items-center sm:gap-4 sm:flex">
          <p class="text-2xl font-extrabold text-gray-900 sm:text-3xl dark:text-white">
            $<%= @product.price %>
          </p>
        </div>

        <div class="mt-6 sm:gap-4 sm:items-center sm:flex sm:mt-8">
          <a
            href="<%= cancel_product_path @product %>"
            data-turbo-method="delete"
            class="
              flex items-center justify-center py-2.5 px-5 text-sm font-medium text-gray-900
              focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100
              hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-100
              dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400
              dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700
            "
            role="button"
          >
            Cancel
          </a>
        </div>

        <hr class="my-6 md:my-8 border-gray-200 dark:border-gray-800"/>

        <p class="mb-6 text-gray-500 dark:text-gray-400">
          Press the Green button on POS machine to pay with Ecocash
        </p>

        <p class="text-gray-500 dark:text-gray-400">
          Tap or insert card to pay with card
        </p>
      </div>
    </div>
  </div>
</section>